### ISSUE TITLE
Validar cenário de comentários onde foram inseridos comentários em pull requests que já foram scaneados

### ISSUE THREAD

**Issue by wesleyeduardocr7** [decioluckow/divulgit#31]

**Comment by wesleyeduardocr7** [comment]
Ao que me parece após fazer o escaneamento de um PR, se fizer um comentário nesse mesmo PR após esse scan, os comentários não vem mais,

**Comment by decioluckow** [comment]
Algumas opções para solução:
- procurar por algum indicador de "ultima alteração" no merge request, que indique que pode ter entrado um novo comentario depois do ultimo scan
- rescanear todos os PRs sempre (não é uma boa opcao)
- criar opção para forçar a carga de algum PR, válido se alguém sentiu a falta de um comentário que fez

**Comment by decioluckow** [comment]
depende da #38
