### ISSUE TITLE
Na tela inicial, procurar um espaço na parte inferir e incluir a logo dos versionadoresde códigos disponíveis no divulgit

### ISSUE THREAD

**Issue by wesleyeduardocr7** [decioluckow/divulgit#35]

**Comment by decioluckow** [comment]
Criar uma tela mais "comercial" para o divulgit e colocar como capa do projeto. Interessante se basear na tela inicial atual (sugestão), incluindo mais informações e quais são as plataformas que ele se comunica. Uma lista de "quem está usando" também seria interessante.

**Comment by decioluckow** [comment]
em andamento

**Comment by decioluckow** [comment]
duplicada
