### ISSUE TITLE
Botão de recarregar merge request não aparenta execução e não faz o refresh da tela.

### ISSUE THREAD

**Issue by decioluckow** [decioluckow/divulgit#56]
Apesar de funcionar corretamente é necessário fazer um refresh da tela para mostrar os dados atualizados. Este não é o principal problema. O problema é que parece que não funcionou (pois nao tem feedback) e o usuário pode ficar clicando muito no botão.

Em principio seria interessante esconder o botão de reload depois de acionado, para expressar algum feedback e impedir que seja acionado novamente. Depois do reload da tela ele estará novamente disponível.

Ao migrarmos para react será mais simples atualizar somente o merge request em questão

**Comment by wesleyeduardocr7** [comment]
resolvido
